import React from 'react';
import { motion } from 'framer-motion';
import { useInView } from 'framer-motion';
import { useRef } from 'react';
import { BookOpen, FileText, ArrowRight, List } from 'lucide-react';

const Definition = () => {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-100px" });

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.2
      }
    }
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0 }
  };

  return (
    <div ref={ref} className="min-h-screen flex items-center justify-center px-4 py-20 relative">
      {/* Section gradient overlay */}
      <div className="absolute inset-0 bg-gradient-to-b from-transparent via-primary-500/5 to-transparent" />
      
      <div className="max-w-6xl mx-auto relative z-10">
        <motion.div
          variants={containerVariants}
          initial="hidden"
          animate={isInView ? "visible" : "hidden"}
        >
          {/* Title */}
          <motion.h2
            variants={itemVariants}
            className="text-5xl md:text-6xl font-bold text-center mb-12 gradient-text"
          >
            Context-Free Grammar & Language
          </motion.h2>

          {/* Two Core Concepts */}
          <motion.div
            variants={itemVariants}
            className="grid md:grid-cols-2 gap-6 mb-8"
          >
            {/* Context-Free Grammar */}
            <div className="glass-dark rounded-2xl shadow-glow p-8 border-l-4 border-primary-500">
              <div className="flex items-start space-x-3 mb-4">
                <FileText className="text-primary-400 flex-shrink-0 mt-1" size={28} />
                <div>
                  <h3 className="text-2xl font-bold text-primary-400 mb-2">Context-Free Grammar</h3>
                  <p className="text-sm text-text-muted mb-3">The Rules (How to Generate)</p>
                </div>
              </div>
              <p className="text-text-secondary leading-relaxed mb-4">
                A <strong className="text-primary-400">formal system</strong> consisting of production rules 
                that describe how to form strings. Think of it as the <strong>recipe or blueprint</strong>.
              </p>
              <div className="glass rounded-lg p-4 border-glow">
                <p className="text-sm text-text-muted mb-2">Example Grammar:</p>
                <div className="font-mono text-accent-400 space-y-1">
                  <p>S → aSb</p>
                  <p>S → ε</p>
                </div>
                <p className="text-xs text-text-muted mt-2">These are the <strong>rules</strong> for generation</p>
              </div>
            </div>

            {/* Context-Free Language */}
            <div className="glass-dark rounded-2xl shadow-glow p-8 border-l-4 border-accent-400">
              <div className="flex items-start space-x-3 mb-4">
                <List className="text-accent-400 flex-shrink-0 mt-1" size={28} />
                <div>
                  <h3 className="text-2xl font-bold text-accent-400 mb-2">Context-Free Language</h3>
                  <p className="text-sm text-text-muted mb-3">The Strings (What is Generated)</p>
                </div>
              </div>
              <p className="text-text-secondary leading-relaxed mb-4">
                A <strong className="text-accent-400">set of strings</strong> that can be generated by a CFG. 
                Think of it as the <strong>result or output</strong> of applying the grammar.
              </p>
              <div className="glass rounded-lg p-4 border-glow">
                <p className="text-sm text-text-muted mb-2">Language Generated:</p>
                <div className="font-mono text-accent-400 space-y-1">
                  <p>L = {'{'} ε, ab, aabb, aaabbb, ... {'}'}</p>
                  <p>L = {'{'} a<sup>n</sup>b<sup>n</sup> | n ≥ 0 {'}'}</p>
                </div>
                <p className="text-xs text-text-muted mt-2">This is the <strong>set of valid strings</strong></p>
              </div>
            </div>
          </motion.div>

          {/* Relationship Diagram */}
          <motion.div
            variants={itemVariants}
            className="glass-dark rounded-2xl shadow-glow p-8 mb-8 border-glow"
          >
            <h3 className="text-2xl font-semibold text-text-primary mb-6 text-center">
              How They Relate
            </h3>
            <div className="flex items-center justify-center gap-6 flex-wrap">
              <div className="glass rounded-xl p-6 text-center border-2 border-primary-500">
                <FileText className="text-primary-400 mx-auto mb-2" size={32} />
                <p className="font-mono text-primary-400 font-bold">Grammar (CFG)</p>
                <p className="text-xs text-text-muted mt-1">The Rules</p>
              </div>
              
              <ArrowRight className="text-accent-400" size={40} />
              
              <div className="glass-dark rounded-xl px-6 py-4 border-2 border-accent-400">
                <p className="text-accent-400 font-semibold text-center">generates</p>
              </div>
              
              <ArrowRight className="text-accent-400" size={40} />
              
              <div className="glass rounded-xl p-6 text-center border-2 border-accent-400">
                <List className="text-accent-400 mx-auto mb-2" size={32} />
                <p className="font-mono text-accent-400 font-bold">Language (CFL)</p>
                <p className="text-xs text-text-muted mt-1">The Strings</p>
              </div>
            </div>
            <p className="text-center text-text-secondary mt-6 max-w-2xl mx-auto">
              A <strong className="text-primary-400">Grammar</strong> is like a recipe that <strong className="text-accent-400">generates</strong> a 
              <strong className="text-accent-400"> Language</strong> (set of strings). Multiple grammars can generate the same language!
            </p>
          </motion.div>

          {/* Introduction */}
          <motion.div
            variants={itemVariants}
            className="glass-dark rounded-2xl shadow-glow p-8 md:p-10 mb-8 hover-glow"
          >
            <div className="flex items-start space-x-4 mb-6">
              <BookOpen className="text-accent-400 flex-shrink-0 mt-1" size={32} />
              <div>
                <h3 className="text-2xl font-semibold text-text-primary mb-4">Why Are They Important?</h3>
                <p className="text-lg text-text-secondary leading-relaxed">
                  Context-Free Grammars and Languages form the theoretical foundation of programming languages, 
                  compilers, and natural language processing. Understanding both the <strong className="text-primary-400">grammar</strong> (how to generate) 
                  and the <strong className="text-accent-400">language</strong> (what is generated) is essential for computer science.
                </p>
              </div>
            </div>
          </motion.div>

          {/* Formal Definitions */}
          <motion.div
            variants={itemVariants}
            className="relative rounded-2xl shadow-glow-lg p-8 md:p-10 mb-8 overflow-hidden"
            style={{
              background: 'linear-gradient(135deg, rgba(99, 102, 241, 0.2), rgba(34, 211, 238, 0.1))',
              border: '1px solid rgba(99, 102, 241, 0.3)',
            }}
          >
            <h3 className="text-2xl font-semibold mb-6 flex items-center text-text-primary">
              <FileText className="mr-3 text-accent-400" size={28} />
              Formal Definitions
            </h3>
            
            {/* CFG Definition */}
            <div className="glass rounded-xl p-6 font-mono text-lg border-glow mb-6">
              <p className="text-sm text-text-muted mb-2">Context-Free Grammar:</p>
              <p className="mb-4 text-center text-2xl text-accent-400">CFG = (V, Σ, R, S)</p>
              <div className="space-y-3 text-base text-text-secondary">
                <p><strong className="text-primary-400">V</strong> = Finite set of <em className="text-accent-400">variables</em> (non-terminals)</p>
                <p><strong className="text-primary-400">Σ</strong> = Finite set of <em className="text-accent-400">terminals</em> (alphabet)</p>
                <p><strong className="text-primary-400">R</strong> = Finite set of <em className="text-accent-400">production rules</em></p>
                <p><strong className="text-primary-400">S</strong> = <em className="text-accent-400">Start symbol</em> (S ∈ V)</p>
              </div>
            </div>

            {/* PDA Definition */}
            <div className="glass rounded-xl p-6 font-mono text-lg border-glow">
              <p className="text-sm text-text-muted mb-2">Pushdown Automaton (Recognition Device for CFLs):</p>
              <p className="mb-4 text-center text-2xl text-accent-400">PDA = (Q, Σ, Γ, δ, q₀, Z, F)</p>
              <div className="space-y-3 text-base text-text-secondary">
                <p><strong className="text-primary-400">Q</strong> = Finite set of <em className="text-accent-400">states</em></p>
                <p><strong className="text-primary-400">Σ</strong> = Input <em className="text-accent-400">alphabet</em></p>
                <p><strong className="text-primary-400">Γ</strong> = Stack <em className="text-accent-400">alphabet</em></p>
                <p><strong className="text-primary-400">δ</strong> = <em className="text-accent-400">Transition function</em>: Q × (Σ ∪ {'{'}ε{'}'}) × Γ → P(Q × Γ*)</p>
                <p><strong className="text-primary-400">q₀</strong> = <em className="text-accent-400">Initial state</em> (q₀ ∈ Q)</p>
                <p><strong className="text-primary-400">Z</strong> = <em className="text-accent-400">Initial stack symbol</em></p>
                <p><strong className="text-primary-400">F</strong> = Set of <em className="text-accent-400">accepting states</em> (F ⊆ Q)</p>
              </div>
              <p className="text-xs text-text-muted mt-4 text-center">
                A PDA is essentially a finite automaton with a <strong className="text-accent-400">stack</strong> for memory
              </p>
            </div>
          </motion.div>
        </motion.div>
      </div>
    </div>
  );
};

export default Definition;
